---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  namespace: "vox",
  resources: [
    "namespace.yaml",
    "persistentvolume.yaml",
    "persistentvolumeclaim.yaml",
    "deployment.yaml",
    "service.yaml",
    "httproute.yaml",
    "dnsendpoint.yaml",
  ],
  images: [{
    name: "docker.io/vllm/vllm-omni",
    newTag: "v0.30.0@sha256:fc77cfaac7b1b43c30cbf32eaea214864434c6e0f303e6e9eb9f64104241a994",
  }],
  configMapGenerator: [{
    name: "deploy-config",
    files: [
      "qwen3_tts.yaml",
    ],
  }],
}
