apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llama-server
  namespace: llama-server
spec:
  ingressClassName: ${INGRESS_CLASS}
  rules:
    - host: ${INGRESS_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llama-server
                port:
                  number: 8080
