---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  namespace: "llama-server",
  configurations: [
    "servicemonitor-secretref.yaml",
  ],
  resources: [
    "namespace.yaml",
    "persistentvolume.yaml",
    "persistentvolumeclaim.yaml",
    "deployment.yaml",
    "service.yaml",
    "servicemonitor.yaml",
    "httproute.yaml",
    "dnsendpoint.yaml",
  ],
  images: [{
    name: "ghcr.io/ggml-org/llama.cpp",
    newTag: "server-cuda13-b11429@sha256:9d6ca9a08b5e0c0a6d2560bff7d4c76bdf946776bbde6a20d9d6403594d93a9f",
  }],
  configMapGenerator: [{
    name: "models-config",
    files: [
      "models.ini",
    ],
  }],
  secretGenerator: [{
    name: "llama-server-key",
    envs: [
      ".env",
    ],
  }],
}
