---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  namespace: "llama-server",
  configurations: [
    "servicemonitor-secretref.yaml",
  ],
  resources: [
    "namespace.yaml",
    "persistentvolume.yaml",
    "persistentvolumeclaim.yaml",
    "deployment.yaml",
    "service.yaml",
    "servicemonitor.yaml",
    "httproute.yaml",
    "dnsendpoint.yaml",
  ],
  images: [{
    name: "ghcr.io/ggml-org/llama.cpp",
    newTag: "server-cuda13-v0.5.0@sha256:24d44a989814a55d73c247ce6b3add72b08db3a491ec8f2b655d574cb71e9252",
  }],
  configMapGenerator: [{
    name: "models-config",
    files: [
      "models.ini",
    ],
  }],
  secretGenerator: [{
    name: "llama-server-key",
    envs: [
      ".env",
    ],
  }],
}
