---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  namespace: "llama-server",
  configurations: [
    "servicemonitor-secretref.yaml",
  ],
  resources: [
    "namespace.yaml",
    "persistentvolume.yaml",
    "persistentvolumeclaim.yaml",
    "deployment.yaml",
    "service.yaml",
    "servicemonitor.yaml",
    "httproute.yaml",
    "dnsendpoint.yaml",
  ],
  images: [{
    name: "ghcr.io/ggml-org/llama.cpp",
    newTag: "server-cuda13-b10588@sha256:6b0d70753bee71cb0b5890ecc0220da751fb99059403b1fd201b33a771b7cb53",
  }],
  configMapGenerator: [{
    name: "models-config",
    files: [
      "models.ini",
    ],
  }],
  secretGenerator: [{
    name: "llama-server-key",
    envs: [
      ".env",
    ],
  }],
}
