version = 1

[*]
parallel = 1

; Gemma
; Gemma 4
[Gemma-4-E2B]
hf-repo = unsloth/gemma-4-E2B-it-qat-GGUF:UD-Q4_K_XL
ctx-size = 131072
n-predict = 32768
temperature = 1.0
top-p = 0.95
top-k = 64
; MTP start
spec-type = draft-mtp
spec-draft-n-max = 2
; MTP end

[Gemma-4-E4B]
hf-repo = unsloth/gemma-4-E4B-it-qat-GGUF:UD-Q4_K_XL
ctx-size = 131072
n-predict = 32768
temperature = 1.0
top-p = 0.95
top-k = 64
; MTP start
spec-type = draft-mtp
spec-draft-n-max = 2
; MTP end

[Gemma-4-12B]
hf-repo = unsloth/gemma-4-12B-it-qat-GGUF:UD-Q4_K_XL
ctx-size = 262144
n-predict = 32768
temperature = 1.0
top-p = 0.95
top-k = 64
; MTP start
spec-type = draft-mtp
spec-draft-n-max = 2
; MTP end

[Gemma-4-26B-A4B]
hf-repo = unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL
no-mmproj-offload = true
ctx-size = 262144
n-predict = 32768
temperature = 1.0
top-p = 0.95
top-k = 64
; MTP start
spec-type = draft-mtp
spec-draft-n-max = 2
; MTP end

[Gemma-4-31B]
hf-repo = unsloth/gemma-4-31B-it-qat-GGUF:UD-Q4_K_XL
no-mmproj-offload = true
ctx-size = 262144
n-predict = 32768
temperature = 1.0
top-p = 0.95
top-k = 64
; MTP start
spec-type = draft-mtp
spec-draft-n-max = 2
; MTP end

; Qwen
; Qwen 3.6
[Qwen-3.6-27B]
hf-repo = unsloth/Qwen3.6-27B-MTP-GGUF:IQ4_NL
no-mmproj-offload = true
ctx-size = 262144
n-predict = 32768
temperature = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
; MTP start
spec-type = draft-mtp
spec-draft-n-max = 2
; MTP end

[Qwen-3.6-35B-A3B]
hf-repo = unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_XL
no-mmproj-offload = true
ctx-size = 262144
n-predict = 32768
temperature = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
; MTP start
spec-type = draft-mtp
spec-draft-n-max = 2
; MTP end
