apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-models
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-models
  local:
    path: /opt/models/huggingface
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nvidia.com/gpu
              operator: Exists
