---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  namespace: "cloudflared",
  resources: [
    "namespace.yaml",
    "deployment.yaml",
  ],
  images: [{
    name: "docker.io/cloudflare/cloudflared",
    newTag: "2026.8.3@sha256:51c9cefcb4569df44e1ad403ab1d3d8065aa8e84339bcfc6aee75502e1140339",
  }],
  configMapGenerator: [{
    name: "cloudflared-config",
    files: [
      "config.yaml",
    ],
  }],
  secretGenerator: [{
    name: "cloudflared-credentials",
    files: [
      "credentials.json",
    ],
  }],
}
