apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth-staging
resources:
  - ../../base
  - namespace.yaml
images:
  - name: auth-service
    newTag: latest
patches:
  - path: deployment-patch.yaml
secretGenerator:
  - name: auth-db-credentials
    envs:
      - .env
