---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  namespace: "hermes",
  resources: [
    "namespace.yaml",
    "persistentvolumeclaim.yaml",
    "deployment.yaml",
    "service.yaml",
    "httproute.yaml",
    "dnsendpoint.yaml",
  ],
  images: [{
    name: "docker.io/nousresearch/hermes-agent",
    newTag: "v2026.9.24@sha256:fca358f12efd65bfaaca05884166f15c0e2788375ca30d77061ac1ebc96452b7",
  }],
  secretGenerator: [{
    name: "hermes-secrets",
    envs: [
      ".env",
    ],
  }],
}
