---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  namespace: "hermes",
  resources: [
    "namespace.yaml",
    "persistentvolumeclaim.yaml",
    "deployment.yaml",
    "service.yaml",
    "httproute.yaml",
    "dnsendpoint.yaml",
  ],
  images: [{
    name: "docker.io/nousresearch/hermes-agent",
    newTag: "v2026.9.7@sha256:63bfb6d732f49a55d453e801057273785cc61e0f6ee43db3fa2f2a79846301b7",
  }],
  secretGenerator: [{
    name: "hermes-secrets",
    envs: [
      ".env",
    ],
  }],
}
